### ISSUE TITLE
Strange Fatal error: Did you forget to Configure XS2A by calling `XS2A.configure(withConfig:withStyle:)`? on `AutocompleteView`

### ISSUE THREAD

**Issue by pawelczerwinskivodeno** [FinTecSystems/xs2a-ios#20] opened 2023-02-05 10:40 UTC
Hello. I have strange crash on project that I've inherited. As for now i don't really understand why my company is using XS2A. From my understanding this functionality was implemented and tested about 1 year ago so this shouldn't be trivial issue like "call configure"

I see multiple crashes 
`Fatal error: Did you forget to Configure XS2A by calling XS2A.configure(withConfig:withStyle:)?`

This crash is reproduced in following way.
1. We present `XS2AViewController`
2. Immediately we see session error `Der Vorgang konnte nicht abgeschlossen werden. (XS2AiOS.XS2ASessionError-Fehler 4.)` that we ignore
3. User taps search field named `Bankname, BIC oder BLZ` pre-filled with `BELADEBEXXX`
4. if user trues to delete text by hitting backspace. Application will crash around text `"B"` or `""`
5. Debugger will halt on `AutocompleteView.tableView(_ tableView:, cellForRowAt:) -> UITableViewCell`
on line `let cell = resultTable.dequeueReusableCell(withIdentifier: "resultCell") as! ResultCell`.
I've added random `print("debug")` in `AutocompleteView` and changed message in `fatalError`

To my surprise after running I've seen `print("debug")` yet fatalError had unchanged message.

we are usnig 
```
  - XS2AiOS (1.11.0):
    - KeychainAccess (= 4.2.2)
    - NVActivityIndicatorView (= 5.1.1)
    - SwiftyJSON (= 5.0.1)
    - XS2AiOSNetService (= 1.0.7)
  - XS2AiOSNetService (1.0.7)
```

We are also manually adding IDNow ( https://github.com/idnow/de.idnow.ios.sdk.spm ), that is using `XS2AiOSNetService`.

Right now I'm investigating if we have some kind of linking issues but maybe You have idea how to solve my issue.
Thanks in advance and have a good day :)

**Comment by fritzfelix** [comment] 2023-02-22 09:25
@pawelczerwinskivodeno Sorry for the late reply, does the issue still persist?

> Immediately we see session error Der Vorgang konnte nicht abgeschlossen werden. (XS2AiOS.XS2ASessionError-Fehler 4.) that we ignore

That sounds like an expired Wizard Session Key.

**Comment by fritzfelix** [comment] 2023-04-13 07:42
Closing this, feel free to reopen if issue occurs again.

**Closed by fritzfelix** 2023-04-13 07:43 UTC

**Comment by biancafelecanwd** [comment] 2023-07-20 07:55
I'm integrating XS2A the same way, using the package and IDNow manually as it's not working otherwise because it integrates XS2AiOSNetService as well.

I'm having the same issue, **without** the 'Immediately we see session error Der Vorgang konnte nicht abgeschlossen werden. (XS2AiOS.XS2ASessionError-Fehler 4.)' console log. It keeps crashing at line '**let cell = resultTable.dequeueReusableCell(withIdentifier: "resultCell") as! ResultCell**'.

Was the expired wizzard session key the cause you've identified? @fritzfelix @pawelczerwinskivodeno?

**Comment by fritzfelix** [comment] 2023-07-25 07:01
@biancafelecanwd Indeed it could be the expired key again. I think its only valid for 9 minutes or so.

**Comment by biancafelecanwd** [comment] 2023-07-26 06:19
It seems it's because we're also importing the IDNow sdk manually. I think the IDNow team should update their package (they also use xs2a but don't expose it properly) so we're able to use their package along with xs2a without dependency issues
